var rgtClick = [
			{
				"name":"新建文件夹"
			},
			{
			    "name":"查看",
			    "span":"",
			    child:[
			            {
			                "name":"大图标"
			            },
			            {
			                "name":"中等图标"
			            },
			            {
			                "name":"小图标"
			            },
			            {
			                "name":"自动排列图标"
			            },
			            {
			                "name":"将图标与网格对齐"
			            },
			            {
			                "name":"显示桌面图标"
			            },
			            {
			                "name":"显示桌面小工具"
			            }
			        ]
			},
			{
			    "name":"排序方式",
			    "span":"",
			    child:[
			            {
			                "name":"名称"
			            },
			            {
			                "name":"类型"
			            },
			            {
			                "name":"项目类型"
			            },
			            {
			                "name":"修改日期"
			            }
			        ]
			
			},
			{
			    "name":"刷新"
			},
			{
			    "name":"图形选项",
			    "span":"",
			    child:[
			            {
			                "name":"屏面适应",
			                "span":"",
			                child:[
			                        {"name":"保持显示缩放比"}
			                    ]
			            },
			            {
			                "name":"快捷键",
			                "span":"",
			                child:[
			                        {
			                            "name":"启用"
			                        },
			                        {
			                            "name":"禁用"
			                        }
			                    ]
			            },
			            {
			                "name":"系统拖盘图标",
			                "span":"",
			                child:[
			                        {
			                            "name":"启用"
			                        },{
			                            "name":"禁用"
			                        }
			                    ]
			            },
			            {
			                "name":"气球通知",
			                "span":"",
			                child:[
			                        {
			                            "name":"图形属性通知",
			                            "span":"",
			                             child:[
			                                    {
			                                        "name":"启用"
			                                    },
			                                    {
			                                        "name":"禁用"
			                                    }
			                                ]
			                        },
			                        {
			                            "name":"最佳分辨率通知",
			                            "span":"",
			                             child:[
			                                    {
			                                        "name":"启用"
			                                    },
			                                    {
			                                        "name":"禁用"
			                                    }
			                                ]
			                        }
			                    ]
			            },{
			                "name":"旋转",
			                "span":"",
			                child:[
			                        {
			                            "name":"旋转至正常"
			                        },
			                        {
			                            "name":"旋转至90度"
			                        },
			                        {
			                            "name":"旋转至180度"
			                        },
			                        {
			                            "name":"旋转至270度"
			                        }
			                    ]
			            }
			        ]
			
			},
			{
			    "name":"个性化"
			}
 ];